# Generated by Django 5.2.8 on 2025-11-06 16:14

import os

from django.conf import settings
from django.db import migrations, models
from dotenv import load_dotenv
from googleapiclient.discovery import build

from youtube.models import static_storage


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# youtube.migrations.0002_populate_regions
def load_regions(apps, schema_editor):
    load_dotenv()

    api_key = settings.YOUTUBE_API_KEY
    Region = apps.get_model("youtube", "Region")

    youtube = build("youtube", "v3", developerKey=api_key)
    response = youtube.i18nRegions().list(part="snippet").execute()
    items = response.get("items", [])

    if not items:
        raise RuntimeError("No region data returned from YouTube API.")

    for item in items:
        code = item["id"]
        title = item["snippet"]["name"]

        static_base = settings.STATIC_BASE_DIR

        static_dir = os.path.join(static_base, "regions", "flags")
        os.makedirs(static_dir, exist_ok=True)
        thumb_path = os.path.join(static_dir, f"{code.lower()}.png")

        Region.objects.update_or_create(
            code=code, defaults={"title": title, "thumb_path": thumb_path}
        )


def unload_regions(apps, schema_editor):
    Region = apps.get_model("youtube", "Region")
    Region.objects.all().delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('thumb_path', models.ImageField(null=True, storage=static_storage, upload_to='regions/flags')),
            ],
        ),
        migrations.RunPython(load_regions, reverse_code=unload_regions),
    ]
