# Generated by Django 5.2.8 on 2025-11-06 16:23
from django.conf import settings
from django.db import migrations, models
from dotenv import load_dotenv
from googleapiclient.discovery import build


def load_categories(apps, schema_editor):
    load_dotenv()

    api_key = settings.YOUTUBE_API_KEY
    Category = apps.get_model("youtube", "Category")

    youtube = build("youtube", "v3", developerKey=api_key)
    response = youtube.videoCategories().list(
        part="snippet",
        regionCode="US"  # You can adjust or iterate over your Region model later
    ).execute()

    items = response.get("items", [])
    if not items:
        raise RuntimeError("No category data returned from YouTube API.")

    for item in items:
        category_id = item["id"]
        snippet = item["snippet"]
        title = snippet["title"]

        Category.objects.update_or_create(
            id=category_id,
            defaults={"title": title},
        )


def unload_categories(apps, schema_editor):
    Category = apps.get_model("youtube", "Category")
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_create_and_populate_youtube_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RunPython(load_categories, reverse_code=unload_categories),
    ]
