# Generated by Django 5.2.8 on 2025-11-06 17:51

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_create_and_populate_youtube_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('channel_id', models.CharField(max_length=50)),
                ('channel_title', models.CharField(max_length=200)),
                ('thumb_url', models.URLField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.category')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.region')),
            ],
        ),
    ]
