# Generated by Django 5.2.8 on 2025-11-07 11:52

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_create_youtube_video_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comments_count', models.IntegerField()),
                ('views_count', models.IntegerField()),
                ('likes_count', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.video')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['video', 'timestamp'], name='youtube_vid_video_i_775535_idx')],
            },
        ),
    ]
