# Generated by Django 5.2.8 on 2025-11-09 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_create_youtube_video_stats_snapshot_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='region',
        ),
        migrations.AlterField(
            model_name='videostatssnapshot',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_snapshots', to='youtube.region'),
        ),
    ]
